package com.nightstory.app.ui.localization

import androidx.compose.runtime.staticCompositionLocalOf

val LocalStrings = staticCompositionLocalOf { AppStrings.english() }

data class AppStrings(
    // App
    val appName: String,
    val appTagline: String,
    // Home
    val storyPromptLabel: String,
    val storyPromptPlaceholder: String,
    val generateButton: String,
    val generatingText: String,
    val readAloudButton: String,
    val stopButton: String,
    val generatingVoiceText: String,
    val newStoryButton: String,
    // Settings
    val settingsTitle: String,
    val settingsSubtitle: String,
    val storyGenerationSection: String,
    val geminiApiKeyLabel: String,
    val geminiApiKeyPlaceholder: String,
    val geminiApiKeyHelper: String,
    val geminiModelLabel: String,
    val storyPreferencesSection: String,
    val storyLanguageLabel: String,
    val storyStyleLabel: String,
    val voiceSection: String,
    val voiceSectionSubtitle: String,
    val ttsProviderLabel: String,
    val ttsDeviceLabel: String,
    val ttsOpenAILabel: String,
    val ttsGoogleLabel: String,
    val openaiApiKeyLabel: String,
    val openaiBaseUrlLabel: String,
    val ttsModelLabel: String,
    val voiceLabel: String,
    val speedLabel: String,
    val googleApiKeyLabel: String,
    val googleApiKeyPlaceholder: String,
    val googleApiKeyHelper: String,
    val googleVoiceLabel: String,
    val languageLabel: String,
    val saveButton: String,
    val savedButton: String,
    val apiConfigSection: String,
    // History
    val storyLibraryTitle: String,
    val storyCount: String,
    val deleteStoryTitle: String,
    val deleteStoryMessage: String,
    val deleteAllTitle: String,
    val deleteAllMessage: String,
    val deleteAllButton: String,
    val emptyLibraryTitle: String,
    val emptyLibrarySubtitle: String,
    val showLess: String,
    val readMore: String,
    val readAloud: String,
    val promptPrefix: String,
    val deleteButton: String,
    val cancelButton: String,
    // Story Styles
    val styleFairyTale: String,
    val styleAdventure: String,
    val styleFunny: String,
    val styleSpooky: String,
    val styleAnimal: String,
    val styleSpace: String,
    val stylePrincess: String,
    val styleDinosaur: String,
    val styleOcean: String,
    val styleMagic: String,
    // Nav
    val navHome: String,
    val navHistory: String,
    val navSettings: String
) {
    companion object {
        fun english() = AppStrings(
            appName = "Night Story",
            appTagline = "Create magical bedtime stories",
            storyPromptLabel = "What should the story be about?",
            storyPromptPlaceholder = "e.g. A brave little rabbit who finds a rainbow...",
            generateButton = "Generate Story",
            generatingText = "Creating your story...",
            readAloudButton = "Read Aloud",
            stopButton = "Stop",
            generatingVoiceText = "Generating voice...",
            newStoryButton = "New Story",
            settingsTitle = "Settings",
            settingsSubtitle = "Configure your story generator",
            storyGenerationSection = "Story Generation",
            geminiApiKeyLabel = "Gemini API Key",
            geminiApiKeyPlaceholder = "Paste your Google AI Studio key",
            geminiApiKeyHelper = "Get a free key at aistudio.google.com/apikey",
            geminiModelLabel = "Gemini Model",
            storyPreferencesSection = "Story Preferences",
            storyLanguageLabel = "Story Language",
            storyStyleLabel = "Story Style",
            voiceSection = "Voice (Text-to-Speech)",
            voiceSectionSubtitle = "Choose how stories are read aloud",
            ttsProviderLabel = "TTS Provider",
            ttsDeviceLabel = "Device Voice (Free, offline)",
            ttsOpenAILabel = "OpenAI TTS (API key)",
            ttsGoogleLabel = "Google Cloud TTS (API key)",
            openaiApiKeyLabel = "OpenAI API Key",
            openaiBaseUrlLabel = "API Base URL",
            ttsModelLabel = "TTS Model",
            voiceLabel = "Voice",
            speedLabel = "Speed",
            googleApiKeyLabel = "Google Cloud API Key",
            googleApiKeyPlaceholder = "AIza...",
            googleApiKeyHelper = "Enable Cloud Text-to-Speech API in Google Cloud Console",
            googleVoiceLabel = "Voice",
            languageLabel = "Language",
            saveButton = "Save Settings",
            savedButton = "Saved!",
            apiConfigSection = "API Configuration",
            storyLibraryTitle = "Story Library",
            storyCount = "%d stories saved",
            deleteStoryTitle = "Delete Story",
            deleteStoryMessage = "Delete \"%s\"?",
            deleteAllTitle = "Delete All Stories",
            deleteAllMessage = "Are you sure? This cannot be undone.",
            deleteAllButton = "Delete All",
            emptyLibraryTitle = "No stories yet!",
            emptyLibrarySubtitle = "Go to Home and create your first story",
            showLess = "Show less",
            readMore = "Read more",
            readAloud = "Read Aloud",
            promptPrefix = "Prompt",
            deleteButton = "Delete",
            cancelButton = "Cancel",
            styleFairyTale = "Fairy Tale",
            styleAdventure = "Adventure",
            styleFunny = "Funny",
            styleSpooky = "Spooky (mild)",
            styleAnimal = "Animal Story",
            styleSpace = "Space Adventure",
            stylePrincess = "Princess & Knight",
            styleDinosaur = "Dinosaur Story",
            styleOcean = "Ocean Adventure",
            styleMagic = "Magic & Wizards",
            navHome = "Home",
            navHistory = "History",
            navSettings = "Settings"
        )

        fun forLanguage(language: String): AppStrings = when (language) {
            "Persian" -> persian()
            "Arabic" -> arabic()
            "Spanish" -> spanish()
            "French" -> french()
            "German" -> german()
            "Portuguese" -> portuguese()
            "Chinese" -> chinese()
            "Japanese" -> japanese()
            "Korean" -> korean()
            "Hindi" -> hindi()
            "Turkish" -> turkish()
            "Italian" -> italian()
            "Russian" -> russian()
            "Dutch" -> dutch()
            else -> english()
        }

        private fun persian() = english().copy(
            appName = "داستان شب",
            appTagline = "داستان‌های جادویی قبل از خواب بسازید",
            storyPromptLabel = "داستان درباره چه چیزی باشد؟",
            storyPromptPlaceholder = "مثلاً یک خرگوش شجوع که رنگین‌کمان پیدا می‌کند...",
            generateButton = "ساخت داستان",
            generatingText = "در حال ساخت داستان شما...",
            readAloudButton = "بلند بخوان",
            stopButton = "توقف",
            generatingVoiceText = "در حال ساخت صدا...",
            newStoryButton = "داستان جدید",
            settingsTitle = "تنظیمات",
            settingsSubtitle = "پیکربندی سازنده داستان",
            storyGenerationSection = "ساخت داستان",
            geminiApiKeyLabel = "کلید API جمینای",
            geminiApiKeyPlaceholder = "کلید Google AI Studio خود را وارد کنید",
            geminiApiKeyHelper = "کلید رایگان در aistudio.google.com/apikey",
            geminiModelLabel = "مدل جمینای",
            storyPreferencesSection = "تنظیمات داستان",
            storyLanguageLabel = "زبان داستان",
            storyStyleLabel = "سبک داستان",
            voiceSection = "صدا (تبدیل متن به گفتار)",
            voiceSectionSubtitle = "نحوه خواندن داستان‌ها را انتخاب کنید",
            ttsProviderLabel = "ارائه‌دهنده TTS",
            ttsDeviceLabel = "صدا دستگاه (رایگان، آفلاین)",
            ttsOpenAILabel = "OpenAI TTS (کلید API)",
            ttsGoogleLabel = "Google Cloud TTS (کلید API)",
            openaiApiKeyLabel = "کلید API OpenAI",
            openaiBaseUrlLabel = "آدرس پایه API",
            ttsModelLabel = "مدل TTS",
            voiceLabel = "صدا",
            speedLabel = "سرعت",
            googleApiKeyLabel = "کلید API Google Cloud",
            googleApiKeyPlaceholder = "AIza...",
            googleApiKeyHelper = "API تبدیل متن به گفتار ابری را در Google Cloud Console فعال کنید",
            googleVoiceLabel = "صدا",
            languageLabel = "زبان",
            saveButton = "ذخیره تنظیمات",
            savedButton = "ذخیره شد!",
            apiConfigSection = "پیکربندی API",
            storyLibraryTitle = "کتابخانه داستان",
            storyCount = "%d داستان ذخیره شده",
            deleteStoryTitle = "حذف داستان",
            deleteStoryMessage = "\"%s\" حذف شود؟",
            deleteAllTitle = "حذف همه داستان‌ها",
            deleteAllMessage = "آیا مطمئنید؟ این عمل قابل بازگشت نیست.",
            deleteAllButton = "حذف همه",
            emptyLibraryTitle = "هنوز داستانی نیست!",
            emptyLibrarySubtitle = "به خانه بروید و اولین داستان خود را بسازید",
            showLess = "کمتر نشان بده",
            readMore = "بیشتر بخوان",
            readAloud = "بلند بخوان",
            promptPrefix = "پرامپت",
            deleteButton = "حذف",
            cancelButton = "لغو",
            styleFairyTale = "قصه پریان",
            styleAdventure = "ماجراجویی",
            styleFunny = "خنده‌دار",
            styleSpooky = "کمی ترسناک",
            styleAnimal = "داستان حیوانات",
            styleSpace = "ماجراجویی فضایی",
            stylePrincess = "شاهزاده و شوالیه",
            styleDinosaur = "داستان دایناسور",
            styleOcean = "ماجراجویی اقیانوس",
            styleMagic = "جادو و جادوگران",
            navHome = "خانه",
            navHistory = "تاریخچه",
            navSettings = "تنظیمات"
        )

        private fun arabic() = english().copy(
            appName = "ليلة قصة",
            appTagline = "اصنع قصص خرافية قبل النوم",
            storyPromptLabel = "ما الذي يجب أن تكون القصة عنه؟",
            storyPromptPlaceholder = "مثلاً أرنب شجع يجد قوس قزح...",
            generateButton = "إنشاء القصة",
            generatingText = "جارٍ إنشاء قصتك...",
            readAloudButton = "اقرأ بصوت عالٍ",
            stopButton = "إيقاف",
            generatingVoiceText = "جارٍ إنشاء الصوت...",
            newStoryButton = "قصة جديدة",
            settingsTitle = "الإعدادات",
            settingsSubtitle = "قم بتكوين مولد القصص",
            storyGenerationSection = "إنشاء القصص",
            geminiApiKeyLabel = "مفتاح API لـ Gemini",
            geminiApiKeyPlaceholder = "الصق مفتاح Google AI Studio الخاص بك",
            geminiApiKeyHelper = "احصل على مفتاح مجاني في aistudio.google.com/apikey",
            geminiModelLabel = "نموذج Gemini",
            storyPreferencesSection = "تفضيلات القصة",
            storyLanguageLabel = "لغة القصة",
            storyStyleLabel = "نمط القصة",
            voiceSection = "الصوت (تحويل النص إلى كلام)",
            voiceSectionSubtitle = "اختر كيفية قراءة القصص",
            ttsProviderLabel = "مزود TTS",
            ttsDeviceLabel = "صوت الجهاز (مجاني، بدون إنترنت)",
            ttsOpenAILabel = "OpenAI TTS (مفتاح API)",
            ttsGoogleLabel = "Google Cloud TTS (مفتاح API)",
            openaiApiKeyLabel = "مفتاح API لـ OpenAI",
            openaiBaseUrlLabel = "عنوان URL الأساسي",
            ttsModelLabel = "نموذج TTS",
            voiceLabel = "الصوت",
            speedLabel = "السرعة",
            googleApiKeyLabel = "مفتاح API لـ Google Cloud",
            googleApiKeyPlaceholder = "AIza...",
            googleApiKeyHelper = "فعّل واجهة تحويل النص إلى كلام السحابية في Google Cloud Console",
            googleVoiceLabel = "الصوت",
            languageLabel = "اللغة",
            saveButton = "حفظ الإعدادات",
            savedButton = "تم الحفظ!",
            apiConfigSection = "تكوين API",
            storyLibraryTitle = "مكتبة القصص",
            storyCount = "%d قصص محفوظة",
            deleteStoryTitle = "حذف القصة",
            deleteStoryMessage = "هل تريد حذف \"%s\"؟",
            deleteAllTitle = "حذف جميع القصص",
            deleteAllMessage = "هل أنت متأكد؟ لا يمكن التراجع عن هذا الإجراء.",
            deleteAllButton = "حذف الكل",
            emptyLibraryTitle = "لا توجد قصص بعد!",
            emptyLibrarySubtitle = "اذهب إلى الصفحة الرئيسية وأنشئ قصتك الأولى",
            showLess = "عرض أقل",
            readMore = "اقرأ المزيد",
            readAloud = "اقرأ بصوت عالٍ",
            promptPrefix = "الموجه",
            deleteButton = "حذف",
            cancelButton = "إلغاء",
            styleFairyTale = "قصة خرافية",
            styleAdventure = "مغامرة",
            styleFunny = "ممتعة",
            styleSpooky = "مخيفة (خفيفة)",
            styleAnimal = "قصة حيوانات",
            styleSpace = "مغامرة فضائية",
            stylePrincess = "الأميرة والفارس",
            styleDinosaur = "قصة ديناصورات",
            styleOcean = "مغامرة محيطية",
            styleMagic = "سحر وسحرة",
            navHome = "الرئيسية",
            navHistory = "التاريخ",
            navSettings = "الإعدادات"
        )

        private fun spanish() = english().copy(
            appName = "Cuento Nocturno",
            appTagline = "Crea cuentos mágicos para dormir",
            storyPromptLabel = "¿De qué debe ser el cuento?",
            storyPromptPlaceholder = "Ej: Un conejito valiente que encuentra un arcoíris...",
            generateButton = "Crear Cuento",
            generatingText = "Creando tu cuento...",
            readAloudButton = "Leer en Voz Alta",
            stopButton = "Detener",
            generatingVoiceText = "Generando voz...",
            newStoryButton = "Nuevo Cuento",
            settingsTitle = "Ajustes",
            settingsSubtitle = "Configura tu generador de cuentos",
            storyGenerationSection = "Generación de Cuentos",
            geminiApiKeyLabel = "Clave API de Gemini",
            geminiApiKeyPlaceholder = "Pega tu clave de Google AI Studio",
            geminiApiKeyHelper = "Obtén una clave gratis en aistudio.google.com/apikey",
            geminiModelLabel = "Modelo Gemini",
            storyPreferencesSection = "Preferencias del Cuento",
            storyLanguageLabel = "Idioma del Cuento",
            storyStyleLabel = "Estilo del Cuento",
            voiceSection = "Voz (Texto a Voz)",
            voiceSectionSubtitle = "Elige cómo se leen los cuentos",
            ttsProviderLabel = "Proveedor TTS",
            ttsDeviceLabel = "Voz del Dispositivo (Gratis, sin internet)",
            ttsOpenAILabel = "OpenAI TTS (Clave API)",
            ttsGoogleLabel = "Google Cloud TTS (Clave API)",
            openaiApiKeyLabel = "Clave API de OpenAI",
            openaiBaseUrlLabel = "URL Base de API",
            ttsModelLabel = "Modelo TTS",
            voiceLabel = "Voz",
            speedLabel = "Velocidad",
            googleApiKeyLabel = "Clave API de Google Cloud",
            googleApiKeyPlaceholder = "AIza...",
            googleApiKeyHelper = "Activa la API de Texto a Voz en Google Cloud Console",
            googleVoiceLabel = "Voz",
            languageLabel = "Idioma",
            saveButton = "Guardar Ajustes",
            savedButton = "¡Guardado!",
            apiConfigSection = "Configuración API",
            storyLibraryTitle = "Biblioteca de Cuentos",
            storyCount = "%d cuentos guardados",
            deleteStoryTitle = "Eliminar Cuento",
            deleteStoryMessage = "¿Eliminar \"%s\"?",
            deleteAllTitle = "Eliminar Todos",
            deleteAllMessage = "¿Estás seguro? Esta acción no se puede deshacer.",
            deleteAllButton = "Eliminar Todo",
            emptyLibraryTitle = "¡Aún no hay cuentos!",
            emptyLibrarySubtitle = "Ve a Inicio y crea tu primer cuento",
            showLess = "Mostrar menos",
            readMore = "Leer más",
            readAloud = "Leer en Voz Alta",
            promptPrefix = "Indicación",
            deleteButton = "Eliminar",
            cancelButton = "Cancelar",
            styleFairyTale = "Cuento de Hadas",
            styleAdventure = "Aventura",
            styleFunny = "Divertido",
            styleSpooky = "De Miedo (suave)",
            styleAnimal = "Historia de Animales",
            styleSpace = "Aventura Espacial",
            stylePrincess = "Princesa y Caballero",
            styleDinosaur = "Historia de Dinosaurios",
            styleOcean = "Aventura Marina",
            styleMagic = "Magia y Hechiceros",
            navHome = "Inicio",
            navHistory = "Historial",
            navSettings = "Ajustes"
        )

        private fun french() = english().copy(
            appName = "Conte du Soir",
            appTagline = "Créez des contes magiques pour le coucher",
            storyPromptLabel = "De quoi doit parler l'histoire ?",
            storyPromptPlaceholder = "Ex: Un petit lapin courageux qui trouve un arc-en-ciel...",
            generateButton = "Créer l'Histoire",
            generatingText = "Création de votre histoire...",
            readAloudButton = "Lire à Voix Haute",
            stopButton = "Arrêter",
            generatingVoiceText = "Génération de la voix...",
            newStoryButton = "Nouvelle Histoire",
            settingsTitle = "Paramètres",
            settingsSubtitle = "Configurez votre générateur d'histoires",
            storyGenerationSection = "Génération d'Histoires",
            geminiApiKeyLabel = "Clé API Gemini",
            geminiApiKeyPlaceholder = "Collez votre clé Google AI Studio",
            geminiApiKeyHelper = "Obtenez une clé gratuite sur aistudio.google.com/apikey",
            geminiModelLabel = "Modèle Gemini",
            storyPreferencesSection = "Préférences de l'Histoire",
            storyLanguageLabel = "Langue de l'Histoire",
            storyStyleLabel = "Style de l'Histoire",
            voiceSection = "Voix (Synthèse Vocale)",
            voiceSectionSubtitle = "Choisissez comment les histoires sont lues",
            ttsProviderLabel = "Fournisseur TTS",
            ttsDeviceLabel = "Voix de l'Appareil (Gratuit, hors ligne)",
            ttsOpenAILabel = "OpenAI TTS (Clé API)",
            ttsGoogleLabel = "Google Cloud TTS (Clé API)",
            openaiApiKeyLabel = "Clé API OpenAI",
            openaiBaseUrlLabel = "URL de Base de l'API",
            ttsModelLabel = "Modèle TTS",
            voiceLabel = "Voix",
            speedLabel = "Vitesse",
            googleApiKeyLabel = "Clé API Google Cloud",
            googleApiKeyPlaceholder = "AIza...",
            googleApiKeyHelper = "Activez l'API Synthèse Vocale dans Google Cloud Console",
            googleVoiceLabel = "Voix",
            languageLabel = "Langue",
            saveButton = "Enregistrer",
            savedButton = "Enregistré !",
            apiConfigSection = "Configuration API",
            storyLibraryTitle = "Bibliothèque d'Histoires",
            storyCount = "%d histoires enregistrées",
            deleteStoryTitle = "Supprimer l'Histoire",
            deleteStoryMessage = "Supprimer \"%s\" ?",
            deleteAllTitle = "Tout Supprimer",
            deleteAllMessage = "Êtes-vous sûr ? Cette action est irréversible.",
            deleteAllButton = "Tout Supprimer",
            emptyLibraryTitle = "Pas encore d'histoires !",
            emptyLibrarySubtitle = "Allez à Accueil et créez votre première histoire",
            showLess = "Réduire",
            readMore = "Lire la suite",
            readAloud = "Lire à Voix Haute",
            promptPrefix = "Invitation",
            deleteButton = "Supprimer",
            cancelButton = "Annuler",
            styleFairyTale = "Conte de Fées",
            styleAdventure = "Aventure",
            styleFunny = "Drôle",
            styleSpooky = "Effrayant (doux)",
            styleAnimal = "Histoire d'Animaux",
            styleSpace = "Aventure Spatiale",
            stylePrincess = "Princesse et Chevalier",
            styleDinosaur = "Histoire de Dinosaures",
            styleOcean = "Aventure Océanique",
            styleMagic = "Magie et Sorciers",
            navHome = "Accueil",
            navHistory = "Historique",
            navSettings = "Paramètres"
        )

        private fun german() = english().copy(
            appName = "Nachtgeschichte",
            appTagline = "Erstelle magische Schlafenszeitgeschichten",
            storyPromptLabel = "Worum soll die Geschichte gehen?",
            storyPromptPlaceholder = "z.B. Ein mutiges kleines Kaninchen, das einen Regenbogen findet...",
            generateButton = "Geschichte Erstellen",
            generatingText = "Deine Geschichte wird erstellt...",
            readAloudButton = "Vorlesen",
            stopButton = "Stopp",
            generatingVoiceText = "Stimme wird generiert...",
            newStoryButton = "Neue Geschichte",
            settingsTitle = "Einstellungen",
            settingsSubtitle = "Konfiguriere deinen Geschichtengenerator",
            storyGenerationSection = "Geschichtenerstellung",
            geminiApiKeyLabel = "Gemini API-Schlüssel",
            geminiApiKeyPlaceholder = "Füge deinen Google AI Studio Schlüssel ein",
            geminiApiKeyHelper = "Kostenlosen Schlüssel erhalten: aistudio.google.com/apikey",
            geminiModelLabel = "Gemini Modell",
            storyPreferencesSection = "Geschichtenpräferenzen",
            storyLanguageLabel = "Geschichtensprache",
            storyStyleLabel = "Geschichtenstil",
            voiceSection = "Stimme (Text-zu-Sprache)",
            voiceSectionSubtitle = "Wähle wie Geschichten vorgelesen werden",
            ttsProviderLabel = "TTS-Anbieter",
            ttsDeviceLabel = "Gerätestimme (Kostenlos, offline)",
            ttsOpenAILabel = "OpenAI TTS (API-Schlüssel)",
            ttsGoogleLabel = "Google Cloud TTS (API-Schlüssel)",
            openaiApiKeyLabel = "OpenAI API-Schlüssel",
            openaiBaseUrlLabel = "API-Basis-URL",
            ttsModelLabel = "TTS-Modell",
            voiceLabel = "Stimme",
            speedLabel = "Geschwindigkeit",
            googleApiKeyLabel = "Google Cloud API-Schlüssel",
            googleApiKeyPlaceholder = "AIza...",
            googleApiKeyHelper = "Aktiviere die Cloud Text-to-Speech API in der Google Cloud Console",
            googleVoiceLabel = "Stimme",
            languageLabel = "Sprache",
            saveButton = "Einstellungen Speichern",
            savedButton = "Gespeichert!",
            apiConfigSection = "API-Konfiguration",
            storyLibraryTitle = "Geschichtenbibliothek",
            storyCount = "%d Geschichten gespeichert",
            deleteStoryTitle = "Geschichte Löschen",
            deleteStoryMessage = "\"%s\" löschen?",
            deleteAllTitle = "Alle Löschen",
            deleteAllMessage = "Bist du sicher? Dies kann nicht rückgängig gemacht werden.",
            deleteAllButton = "Alle Löschen",
            emptyLibraryTitle = "Noch keine Geschichten!",
            emptyLibrarySubtitle = "Gehe zu Start und erstelle deine erste Geschichte",
            showLess = "Weniger anzeigen",
            readMore = "Weiterlesen",
            readAloud = "Vorlesen",
            promptPrefix = "Eingabe",
            deleteButton = "Löschen",
            cancelButton = "Abbrechen",
            styleFairyTale = "Märchen",
            styleAdventure = "Abenteuer",
            styleFunny = "Lustig",
            styleSpooky = "Gruselig (mild)",
            styleAnimal = "Tiergeschichte",
            styleSpace = "Weltraumabenteuer",
            stylePrincess = "Prinzessin & Ritter",
            styleDinosaur = "Dinosauriergeschichte",
            styleOcean = "Meeresabenteuer",
            styleMagic = "Magie & Zauberer",
            navHome = "Start",
            navHistory = "Verlauf",
            navSettings = "Einstellungen"
        )

        private fun portuguese() = english().copy(
            appName = "Conto Noturno",
            appTagline = "Crie contos mágicos para dormir",
            storyPromptLabel = "Sobre o que deve ser o conto?",
            storyPromptPlaceholder = "Ex: Um coelhinho corajoso que encontra um arco-íris...",
            generateButton = "Criar Conto",
            generatingText = "Criando seu conto...",
            readAloudButton = "Ler em Voz Alta",
            stopButton = "Parar",
            generatingVoiceText = "Gerando voz...",
            newStoryButton = "Novo Conto",
            settingsTitle = "Configurações",
            settingsSubtitle = "Configure seu gerador de contos",
            storyGenerationSection = "Geração de Contos",
            geminiApiKeyLabel = "Chave API Gemini",
            geminiApiKeyPlaceholder = "Cole sua chave do Google AI Studio",
            geminiApiKeyHelper = "Obtenha uma chave gratuita em aistudio.google.com/apikey",
            geminiModelLabel = "Modelo Gemini",
            storyPreferencesSection = "Preferências do Conto",
            storyLanguageLabel = "Idioma do Conto",
            storyStyleLabel = "Estilo do Conto",
            voiceSection = "Voz (Texto para Fala)",
            voiceSectionSubtitle = "Escolha como os contos são lidos",
            ttsProviderLabel = "Provedor TTS",
            ttsDeviceLabel = "Voz do Dispositivo (Grátis, offline)",
            ttsOpenAILabel = "OpenAI TTS (Chave API)",
            ttsGoogleLabel = "Google Cloud TTS (Chave API)",
            openaiApiKeyLabel = "Chave API OpenAI",
            openaiBaseUrlLabel = "URL Base da API",
            ttsModelLabel = "Modelo TTS",
            voiceLabel = "Voz",
            speedLabel = "Velocidade",
            googleApiKeyLabel = "Chave API Google Cloud",
            googleApiKeyPlaceholder = "AIza...",
            googleApiKeyHelper = "Ative a API Text-to-Speech no Google Cloud Console",
            googleVoiceLabel = "Voz",
            languageLabel = "Idioma",
            saveButton = "Salvar Configurações",
            savedButton = "Salvo!",
            apiConfigSection = "Configuração API",
            storyLibraryTitle = "Biblioteca de Contos",
            storyCount = "%d contos salvos",
            deleteStoryTitle = "Excluir Conto",
            deleteStoryMessage = "Excluir \"%s\"?",
            deleteAllTitle = "Excluir Todos",
            deleteAllMessage = "Tem certeza? Esta ação não pode ser desfeita.",
            deleteAllButton = "Excluir Tudo",
            emptyLibraryTitle = "Nenhum conto ainda!",
            emptyLibrarySubtitle = "Vá para Início e crie seu primeiro conto",
            showLess = "Mostrar menos",
            readMore = "Ler mais",
            readAloud = "Ler em Voz Alta",
            promptPrefix = "Prompt",
            deleteButton = "Excluir",
            cancelButton = "Cancelar",
            styleFairyTale = "Conto de Fadas",
            styleAdventure = "Aventura",
            styleFunny = "Engraçado",
            styleSpooky = "Assustador (leve)",
            styleAnimal = "História de Animais",
            styleSpace = "Aventura Espacial",
            stylePrincess = "Princesa e Cavaleiro",
            styleDinosaur = "História de Dinossauros",
            styleOcean = "Aventura Marítima",
            styleMagic = "Magia e Feiticeiros",
            navHome = "Início",
            navHistory = "Histórico",
            navSettings = "Configurações"
        )

        private fun chinese() = english().copy(
            appName = "睡前故事",
            appTagline = "创作魔法般的睡前故事",
            storyPromptLabel = "故事关于什么？",
            storyPromptPlaceholder = "例如：一只勇敢的小兔子发现了一道彩虹...",
            generateButton = "生成故事",
            generatingText = "正在创作你的故事...",
            readAloudButton = "朗读",
            stopButton = "停止",
            generatingVoiceText = "正在生成语音...",
            newStoryButton = "新故事",
            settingsTitle = "设置",
            settingsSubtitle = "配置你的故事生成器",
            storyGenerationSection = "故事生成",
            geminiApiKeyLabel = "Gemini API 密钥",
            geminiApiKeyPlaceholder = "粘贴你的 Google AI Studio 密钥",
            geminiApiKeyHelper = "在 aistudio.google.com/apikey 获取免费密钥",
            geminiModelLabel = "Gemini 模型",
            storyPreferencesSection = "故事偏好",
            storyLanguageLabel = "故事语言",
            storyStyleLabel = "故事风格",
            voiceSection = "语音（文字转语音）",
            voiceSectionSubtitle = "选择故事朗读方式",
            ttsProviderLabel = "TTS 提供商",
            ttsDeviceLabel = "设备语音（免费，离线）",
            ttsOpenAILabel = "OpenAI TTS（API 密钥）",
            ttsGoogleLabel = "Google Cloud TTS（API 密钥）",
            openaiApiKeyLabel = "OpenAI API 密钥",
            openaiBaseUrlLabel = "API 基础 URL",
            ttsModelLabel = "TTS 模型",
            voiceLabel = "语音",
            speedLabel = "语速",
            googleApiKeyLabel = "Google Cloud API 密钥",
            googleApiKeyPlaceholder = "AIza...",
            googleApiKeyHelper = "在 Google Cloud Console 启用文字转语音 API",
            googleVoiceLabel = "语音",
            languageLabel = "语言",
            saveButton = "保存设置",
            savedButton = "已保存！",
            apiConfigSection = "API 配置",
            storyLibraryTitle = "故事库",
            storyCount = "已保存 %d 个故事",
            deleteStoryTitle = "删除故事",
            deleteStoryMessage = "删除「%s」？",
            deleteAllTitle = "删除所有故事",
            deleteAllMessage = "确定吗？此操作无法撤销。",
            deleteAllButton = "全部删除",
            emptyLibraryTitle = "还没有故事！",
            emptyLibrarySubtitle = "去首页创作你的第一个故事",
            showLess = "收起",
            readMore = "阅读更多",
            readAloud = "朗读",
            promptPrefix = "提示",
            deleteButton = "删除",
            cancelButton = "取消",
            styleFairyTale = "童话故事",
            styleAdventure = "冒险",
            styleFunny = "搞笑",
            styleSpooky = "轻微恐怖",
            styleAnimal = "动物故事",
            styleSpace = "太空冒险",
            stylePrincess = "公主与骑士",
            styleDinosaur = "恐龙故事",
            styleOcean = "海洋冒险",
            styleMagic = "魔法与巫师",
            navHome = "首页",
            navHistory = "历史",
            navSettings = "设置"
        )

        private fun japanese() = english().copy(
            appName = "よるのものがたり",
            appTagline = "魔法のような寝前のお話をつくる",
            storyPromptLabel = "お話のテーマは？",
            storyPromptPlaceholder = "例：虹を見つけた勇敢なうさぎ...",
            generateButton = "お話をつくる",
            generatingText = "お話をつくり中...",
            readAloudButton = "声で読む",
            stopButton = "とめる",
            generatingVoiceText = "音声をつくり中...",
            newStoryButton = "新しいお話",
            settingsTitle = "設定",
            settingsSubtitle = "お話ジェネレーターを設定",
            storyGenerationSection = "お話生成",
            geminiApiKeyLabel = "Gemini APIキー",
            geminiApiKeyPlaceholder = "Google AI Studioキーを貼り付け",
            geminiApiKeyHelper = "aistudio.google.com/apikeyで無料キーを取得",
            geminiModelLabel = "Geminiモデル",
            storyPreferencesSection = "お話の設定",
            storyLanguageLabel = "お話の言語",
            storyStyleLabel = "お話のスタイル",
            voiceSection = "音声（テキスト読み上げ）",
            voiceSectionSubtitle = "お話をどう読むか選択",
            ttsProviderLabel = "TTSプロバイダー",
            ttsDeviceLabel = "デバイス音声（無料、オフライン）",
            ttsOpenAILabel = "OpenAI TTS（APIキー）",
            ttsGoogleLabel = "Google Cloud TTS（APIキー）",
            openaiApiKeyLabel = "OpenAI APIキー",
            openaiBaseUrlLabel = "APIベースURL",
            ttsModelLabel = "TTSモデル",
            voiceLabel = "音声",
            speedLabel = "速度",
            googleApiKeyLabel = "Google Cloud APIキー",
            googleApiKeyPlaceholder = "AIza...",
            googleApiKeyHelper = "Google Cloud Consoleでテキスト読み上げAPIを有効化",
            googleVoiceLabel = "音声",
            languageLabel = "言語",
            saveButton = "設定を保存",
            savedButton = "保存済み！",
            apiConfigSection = "API設定",
            storyLibraryTitle = "おはなしライブラリ",
            storyCount = "%d件のお話を保存済み",
            deleteStoryTitle = "お話の削除",
            deleteStoryMessage = "「%s」を削除しますか？",
            deleteAllTitle = "すべて削除",
            deleteAllMessage = "よろしいですか？この操作は元に戻せません。",
            deleteAllButton = "すべて削除",
            emptyLibraryTitle = "まだお話がありません！",
            emptyLibrarySubtitle = "ホームに移動して最初のお話をつくりましょう",
            showLess = "閉じる",
            readMore = "もっと読む",
            readAloud = "声で読む",
            promptPrefix = "プロンプト",
            deleteButton = "削除",
            cancelButton = "キャンセル",
            styleFairyTale = "おとぎ話",
            styleAdventure = "冒険",
            styleFunny = "面白い",
            styleSpooky = "ちょっと怖い",
            styleAnimal = "動物の話",
            styleSpace = "宇宙冒険",
            stylePrincess = "お姫様と騎士",
            styleDinosaur = "恐竜の話",
            styleOcean = "海の冒険",
            styleMagic = "魔法と魔法使い",
            navHome = "ホーム",
            navHistory = "履歴",
            navSettings = "設定"
        )

        private fun korean() = english().copy(
            appName = "밤이야기",
            appTagline = "마법 같은 잠자리 이야기를 만들어요",
            storyPromptLabel = "이야기가 무엇에 관한 것인가요?",
            storyPromptPlaceholder = "예: 무지개를 찾은 용감한 토끼...",
            generateButton = "이야기 만들기",
            generatingText = "이야기를 만들고 있어요...",
            readAloudButton = "소리 내어 읽기",
            stopButton = "중지",
            generatingVoiceText = "음성 생성 중...",
            newStoryButton = "새 이야기",
            settingsTitle = "설정",
            settingsSubtitle = "이야기 생성기 설정",
            storyGenerationSection = "이야기 생성",
            geminiApiKeyLabel = "Gemini API 키",
            geminiApiKeyPlaceholder = "Google AI Studio 키를 붙여넣기",
            geminiApiKeyHelper = "aistudio.google.com/apikey에서 무료 키 받기",
            geminiModelLabel = "Gemini 모델",
            storyPreferencesSection = "이야기 설정",
            storyLanguageLabel = "이야기 언어",
            storyStyleLabel = "이야기 스타일",
            voiceSection = "음성 (텍스트 음성 변환)",
            voiceSectionSubtitle = "이야기 읽기 방법 선택",
            ttsProviderLabel = "TTS 제공자",
            ttsDeviceLabel = "기기 음성 (무료, 오프라인)",
            ttsOpenAILabel = "OpenAI TTS (API 키)",
            ttsGoogleLabel = "Google Cloud TTS (API 키)",
            openaiApiKeyLabel = "OpenAI API 키",
            openaiBaseUrlLabel = "API 기본 URL",
            ttsModelLabel = "TTS 모델",
            voiceLabel = "음성",
            speedLabel = "속도",
            googleApiKeyLabel = "Google Cloud API 키",
            googleApiKeyPlaceholder = "AIza...",
            googleApiKeyHelper = "Google Cloud Console에서 텍스트 음성 변환 API 활성화",
            googleVoiceLabel = "음성",
            languageLabel = "언어",
            saveButton = "설정 저장",
            savedButton = "저장됨!",
            apiConfigSection = "API 설정",
            storyLibraryTitle = "이야기 도서관",
            storyCount = "%d개 이야기 저장됨",
            deleteStoryTitle = "이야기 삭제",
            deleteStoryMessage = "\"%s\"을(를) 삭제하시겠습니까?",
            deleteAllTitle = "모두 삭제",
            deleteAllMessage = "확실하신가요? 이 작업은 되돌릴 수 없습니다.",
            deleteAllButton = "모두 삭제",
            emptyLibraryTitle = "아직 이야기가 없어요!",
            emptyLibrarySubtitle = "홈으로 가서 첫 번째 이야기를 만들어 보세요",
            showLess = "접기",
            readMore = "더 보기",
            readAloud = "소리 내어 읽기",
            promptPrefix = "프롬프트",
            deleteButton = "삭제",
            cancelButton = "취소",
            styleFairyTale = "동화",
            styleAdventure = "모험",
            styleFunny = "재미있는",
            styleSpooky = "약간 무서운",
            styleAnimal = "동물 이야기",
            styleSpace = "우주 모험",
            stylePrincess = "공주와 기사",
            styleDinosaur = "공룡 이야기",
            styleOcean = "바다 모험",
            styleMagic = "마법과 마법사",
            navHome = "홈",
            navHistory = "기록",
            navSettings = "설정"
        )

        private fun hindi() = english().copy(
            appName = "रात की कहानी",
            appTagline = "जादुई सुनने वाली कहानियाँ बनाएँ",
            storyPromptLabel = "कहानी किस बारे में हो?",
            storyPromptPlaceholder = "जैसे: एक बहादुर छोटा खरगोश जो इंद्रधनुष ढूंढता है...",
            generateButton = "कहानी बनाएँ",
            generatingText = "आपकी कहानी बन रही है...",
            readAloudButton = "ज़ोर से पढ़ें",
            stopButton = "रोकें",
            generatingVoiceText = "आवाज़ बन रही है...",
            newStoryButton = "नई कहानी",
            settingsTitle = "सेटिंग्स",
            settingsSubtitle = "अपना कहानी जनरेटर कॉन्फ़िगर करें",
            storyGenerationSection = "कहानी निर्माण",
            geminiApiKeyLabel = "Gemini API कुंजी",
            geminiApiKeyPlaceholder = "अपनी Google AI Studio कुंजी पेस्ट करें",
            geminiApiKeyHelper = "aistudio.google.com/apikey पर मुफ्त कुंजी प्राप्त करें",
            geminiModelLabel = "Gemini मॉडल",
            storyPreferencesSection = "कहानी प्राथमिकताएँ",
            storyLanguageLabel = "कहानी की भाषा",
            storyStyleLabel = "कहानी की शैली",
            voiceSection = "आवाज़ (टेक्स्ट-टू-स्पीच)",
            voiceSectionSubtitle = "कहानियाँ कैसे पढ़ी जाएँ चुनें",
            ttsProviderLabel = "TTS प्रदाता",
            ttsDeviceLabel = "डिवाइस आवाज़ (मुफ्त, ऑफ़लाइन)",
            ttsOpenAILabel = "OpenAI TTS (API कुंजी)",
            ttsGoogleLabel = "Google Cloud TTS (API कुंजी)",
            openaiApiKeyLabel = "OpenAI API कुंजी",
            openaiBaseUrlLabel = "API बेस URL",
            ttsModelLabel = "TTS मॉडल",
            voiceLabel = "आवाज़",
            speedLabel = "गति",
            googleApiKeyLabel = "Google Cloud API कुंजी",
            googleApiKeyPlaceholder = "AIza...",
            googleApiKeyHelper = "Google Cloud Console में टेक्स्ट-टू-स्पीच API सक्षम करें",
            googleVoiceLabel = "आवाज़",
            languageLabel = "भाषा",
            saveButton = "सेटिंग्स सहेजें",
            savedButton = "सहेजा गया!",
            apiConfigSection = "API कॉन्फ़िगरेशन",
            storyLibraryTitle = "कहानी पुस्तकालय",
            storyCount = "%d कहानियाँ सहेजी गईं",
            deleteStoryTitle = "कहानी हटाएँ",
            deleteStoryMessage = "\"%s\" हटाएँ?",
            deleteAllTitle = "सभी हटाएँ",
            deleteAllMessage = "क्या आप सुनिश्चित हैं? यह क्रिया पूर्ववत नहीं की जा सकती।",
            deleteAllButton = "सभी हटाएँ",
            emptyLibraryTitle = "अभी कोई कहानी नहीं!",
            emptyLibrarySubtitle = "होम पर जाएँ और अपनी पहली कहानी बनाएँ",
            showLess = "कम दिखाएँ",
            readMore = "और पढ़ें",
            readAloud = "ज़ोर से पढ़ें",
            promptPrefix = "प्रॉम्प्ट",
            deleteButton = "हटाएँ",
            cancelButton = "रद्द करें",
            styleFairyTale = "परियों की कहानी",
            styleAdventure = "साहसिक",
            styleFunny = "मज़ेदार",
            styleSpooky = "हल्का डरावना",
            styleAnimal = "जानवरों की कहानी",
            styleSpace = "अंतरिक्ष साहसिक",
            stylePrincess = "राजकुमारी और शूरवीर",
            styleDinosaur = "डायनासोर कहानी",
            styleOcean = "समुद्री साहसिक",
            styleMagic = "जादू और जादूगर",
            navHome = "होम",
            navHistory = "इतिहास",
            navSettings = "सेटिंग्स"
        )

        private fun turkish() = english().copy(
            appName = "Gece Masalı",
            appTagline = "Büyülü uyku masalları oluşturun",
            storyPromptLabel = "Masal ne hakkında olsun?",
            storyPromptPlaceholder = "Örn: Gökkuşağı bulan cesur küçük bir tavşan...",
            generateButton = "Masal Oluştur",
            generatingText = "Masalınız oluşturuluyor...",
            readAloudButton = "Sesli Oku",
            stopButton = "Durdur",
            generatingVoiceText = "Ses oluşturuluyor...",
            newStoryButton = "Yeni Masal",
            settingsTitle = "Ayarlar",
            settingsSubtitle = "Masal oluşturucunuzu yapılandırın",
            storyGenerationSection = "Masal Oluşturma",
            geminiApiKeyLabel = "Gemini API Anahtarı",
            geminiApiKeyPlaceholder = "Google AI Studio anahtarınızı yapıştırın",
            geminiApiKeyHelper = "aistudio.google.com/apikey adresinden ücretsiz anahtar alın",
            geminiModelLabel = "Gemini Modeli",
            storyPreferencesSection = "Masal Tercihleri",
            storyLanguageLabel = "Masal Dili",
            storyStyleLabel = "Masal Stili",
            voiceSection = "Ses (Metin Okuma)",
            voiceSectionSubtitle = "Masalların nasıl okunacağını seçin",
            ttsProviderLabel = "TTS Sağlayıcı",
            ttsDeviceLabel = "Cihaz Sesi (Ücretsiz, çevrimdışı)",
            ttsOpenAILabel = "OpenAI TTS (API Anahtarı)",
            ttsGoogleLabel = "Google Cloud TTS (API Anahtarı)",
            openaiApiKeyLabel = "OpenAI API Anahtarı",
            openaiBaseUrlLabel = "API Taban URL",
            ttsModelLabel = "TTS Modeli",
            voiceLabel = "Ses",
            speedLabel = "Hız",
            googleApiKeyLabel = "Google Cloud API Anahtarı",
            googleApiKeyPlaceholder = "AIza...",
            googleApiKeyHelper = "Google Cloud Console'da Metin Okuma API'sini etkinleştirin",
            googleVoiceLabel = "Ses",
            languageLabel = "Dil",
            saveButton = "Ayarları Kaydet",
            savedButton = "Kaydedildi!",
            apiConfigSection = "API Yapılandırması",
            storyLibraryTitle = "Masal Kütüphanesi",
            storyCount = "%d masal kaydedildi",
            deleteStoryTitle = "Masalı Sil",
            deleteStoryMessage = "\"%s\" silinsin mi?",
            deleteAllTitle = "Tümünü Sil",
            deleteAllMessage = "Emin misiniz? Bu işlem geri alınamaz.",
            deleteAllButton = "Tümünü Sil",
            emptyLibraryTitle = "Henüz masal yok!",
            emptyLibrarySubtitle = "Ana sayfaya gidin ve ilk masalınızı oluşturun",
            showLess = "Daha az göster",
            readMore = "Devamını oku",
            readAloud = "Sesli Oku",
            promptPrefix = "İstem",
            deleteButton = "Sil",
            cancelButton = "İptal",
            styleFairyTale = "Peri Masalı",
            styleAdventure = "Macera",
            styleFunny = "Komik",
            styleSpooky = "Hafif Korkunç",
            styleAnimal = "Hayvan Hikayesi",
            styleSpace = "Uzay Macerası",
            stylePrincess = "Prenses ve Şövalye",
            styleDinosaur = "Dinozor Hikayesi",
            styleOcean = "Okyanus Macerası",
            styleMagic = "Büyü ve Büyücüler",
            navHome = "Ana Sayfa",
            navHistory = "Geçmiş",
            navSettings = "Ayarlar"
        )

        private fun italian() = english().copy(
            appName = "Fiaba Notturna",
            appTagline = "Crea fiabe magiche per il sonno",
            storyPromptLabel = "Di cosa parlare la fiaba?",
            storyPromptPlaceholder = "Es: Un coniglietto coraggioso che trova un arcobaleno...",
            generateButton = "Crea Fiaba",
            generatingText = "Creazione della tua fiaba...",
            readAloudButton = "Leggi ad Alta Voce",
            stopButton = "Ferma",
            generatingVoiceText = "Generazione voce...",
            newStoryButton = "Nuova Fiaba",
            settingsTitle = "Impostazioni",
            settingsSubtitle = "Configura il tuo generatore di fiabe",
            storyGenerationSection = "Generazione Fiabe",
            geminiApiKeyLabel = "Chiave API Gemini",
            geminiApiKeyPlaceholder = "Incolla la tua chiave Google AI Studio",
            geminiApiKeyHelper = "Ottieni una chiave gratuita su aistudio.google.com/apikey",
            geminiModelLabel = "Modello Gemini",
            storyPreferencesSection = "Preferenze Fiaba",
            storyLanguageLabel = "Lingua della Fiaba",
            storyStyleLabel = "Stile della Fiaba",
            voiceSection = "Voce (Sintesi Vocale)",
            voiceSectionSubtitle = "Scegli come vengono lette le fiabe",
            ttsProviderLabel = "Provider TTS",
            ttsDeviceLabel = "Voce del Dispositivo (Gratuito, offline)",
            ttsOpenAILabel = "OpenAI TTS (Chiave API)",
            ttsGoogleLabel = "Google Cloud TTS (Chiave API)",
            openaiApiKeyLabel = "Chiave API OpenAI",
            openaiBaseUrlLabel = "URL Base API",
            ttsModelLabel = "Modello TTS",
            voiceLabel = "Voce",
            speedLabel = "Velocità",
            googleApiKeyLabel = "Chiave API Google Cloud",
            googleApiKeyPlaceholder = "AIza...",
            googleApiKeyHelper = "Abilita l'API Sintesi Vocale in Google Cloud Console",
            googleVoiceLabel = "Voce",
            languageLabel = "Lingua",
            saveButton = "Salva Impostazioni",
            savedButton = "Salvato!",
            apiConfigSection = "Configurazione API",
            storyLibraryTitle = "Biblioteca Fiabe",
            storyCount = "%d fiabe salvate",
            deleteStoryTitle = "Elimina Fiaba",
            deleteStoryMessage = "Eliminare \"%s\"?",
            deleteAllTitle = "Elimina Tutte",
            deleteAllMessage = "Sei sicuro? Questa azione non può essere annullata.",
            deleteAllButton = "Elimina Tutto",
            emptyLibraryTitle = "Nessuna fiaba ancora!",
            emptyLibrarySubtitle = "Vai a Home e crea la tua prima fiaba",
            showLess = "Mostra meno",
            readMore = "Leggi di più",
            readAloud = "Leggi ad Alta Voce",
            promptPrefix = "Prompt",
            deleteButton = "Elimina",
            cancelButton = "Annulla",
            styleFairyTale = "Fiaba",
            styleAdventure = "Avventura",
            styleFunny = "Divertente",
            styleSpooky = "Spaventoso (leggero)",
            styleAnimal = "Storia di Animali",
            styleSpace = "Avventura Spaziale",
            stylePrincess = "Principessa e Cavaliere",
            styleDinosaur = "Storia di Dinosauri",
            styleOcean = "Avventura Marina",
            styleMagic = "Magia e Maghi",
            navHome = "Home",
            navHistory = "Cronologia",
            navSettings = "Impostazioni"
        )

        private fun russian() = english().copy(
            appName = "Ночная Сказка",
            appTagline = "Создавайте волшебные сказки на ночь",
            storyPromptLabel = "О чём должна быть сказка?",
            storyPromptPlaceholder = "Напр: Храбрый зайчик, который нашёл радугу...",
            generateButton = "Создать Сказку",
            generatingText = "Создаём вашу сказку...",
            readAloudButton = "Читать Вслух",
            stopButton = "Стоп",
            generatingVoiceText = "Генерация голоса...",
            newStoryButton = "Новая Сказка",
            settingsTitle = "Настройки",
            settingsSubtitle = "Настройте генератор сказок",
            storyGenerationSection = "Создание Сказок",
            geminiApiKeyLabel = "API-ключ Gemini",
            geminiApiKeyPlaceholder = "Вставьте ваш ключ Google AI Studio",
            geminiApiKeyHelper = "Получите бесплатный ключ на aistudio.google.com/apikey",
            geminiModelLabel = "Модель Gemini",
            storyPreferencesSection = "Настройки Сказки",
            storyLanguageLabel = "Язык Сказки",
            storyStyleLabel = "Стиль Сказки",
            voiceSection = "Голос (Синтез Речи)",
            voiceSectionSubtitle = "Выберите, как читать сказки",
            ttsProviderLabel = "Провайдер TTS",
            ttsDeviceLabel = "Голос Устройства (Бесплатно, офлайн)",
            ttsOpenAILabel = "OpenAI TTS (API-ключ)",
            ttsGoogleLabel = "Google Cloud TTS (API-ключ)",
            openaiApiKeyLabel = "API-ключ OpenAI",
            openaiBaseUrlLabel = "Базовый URL API",
            ttsModelLabel = "Модель TTS",
            voiceLabel = "Голос",
            speedLabel = "Скорость",
            googleApiKeyLabel = "API-ключ Google Cloud",
            googleApiKeyPlaceholder = "AIza...",
            googleApiKeyHelper = "Включите API синтеза речи в Google Cloud Console",
            googleVoiceLabel = "Голос",
            languageLabel = "Язык",
            saveButton = "Сохранить Настройки",
            savedButton = "Сохранено!",
            apiConfigSection = "Настройки API",
            storyLibraryTitle = "Библиотека Сказок",
            storyCount = "%d сказок сохранено",
            deleteStoryTitle = "Удалить Сказку",
            deleteStoryMessage = "Удалить «%s»?",
            deleteAllTitle = "Удалить Все",
            deleteAllMessage = "Вы уверены? Это действие нельзя отменить.",
            deleteAllButton = "Удалить Всё",
            emptyLibraryTitle = "Пока нет сказок!",
            emptyLibrarySubtitle = "Перейдите на Главную и создайте первую сказку",
            showLess = "Свернуть",
            readMore = "Читать далее",
            readAloud = "Читать Вслух",
            promptPrefix = "Запрос",
            deleteButton = "Удалить",
            cancelButton = "Отмена",
            styleFairyTale = "Сказка",
            styleAdventure = "Приключение",
            styleFunny = "Смешная",
            styleSpooky = "Немного страшная",
            styleAnimal = "Про животных",
            styleSpace = "Космическое приключение",
            stylePrincess = "Принцесса и Рыцарь",
            styleDinosaur = "Про динозавров",
            styleOcean = "Морское приключение",
            styleMagic = "Магия и Волшебники",
            navHome = "Главная",
            navHistory = "История",
            navSettings = "Настройки"
        )

        private fun dutch() = english().copy(
            appName = "Nachtverhaal",
            appTagline = "Maak magische bedtijdverhalen",
            storyPromptLabel = "Waar moet het verhaal over gaan?",
            storyPromptPlaceholder = "Bijv: Een dapper konijntje dat een regenboog vindt...",
            generateButton = "Verhaal Maken",
            generatingText = "Je verhaal wordt gemaakt...",
            readAloudButton = "Hardop Lezen",
            stopButton = "Stop",
            generatingVoiceText = "Stem genereren...",
            newStoryButton = "Nieuw Verhaal",
            settingsTitle = "Instellingen",
            settingsSubtitle = "Configureer je verhaalgenerator",
            storyGenerationSection = "Verhaal Genereren",
            geminiApiKeyLabel = "Gemini API Sleutel",
            geminiApiKeyPlaceholder = "Plak je Google AI Studio sleutel",
            geminiApiKeyHelper = "Krijg een gratis sleutel op aistudio.google.com/apikey",
            geminiModelLabel = "Gemini Model",
            storyPreferencesSection = "Verhaal Voorkeuren",
            storyLanguageLabel = "Verhaal Taal",
            storyStyleLabel = "Verhaal Stijl",
            voiceSection = "Stem (Tekst-naar-Spraak)",
            voiceSectionSubtitle = "Kies hoe verhalen worden voorgelezen",
            ttsProviderLabel = "TTS Provider",
            ttsDeviceLabel = "Apparaat Stem (Gratis, offline)",
            ttsOpenAILabel = "OpenAI TTS (API Sleutel)",
            ttsGoogleLabel = "Google Cloud TTS (API Sleutel)",
            openaiApiKeyLabel = "OpenAI API Sleutel",
            openaiBaseUrlLabel = "API Basis URL",
            ttsModelLabel = "TTS Model",
            voiceLabel = "Stem",
            speedLabel = "Snelheid",
            googleApiKeyLabel = "Google Cloud API Sleutel",
            googleApiKeyPlaceholder = "AIza...",
            googleApiKeyHelper = "Schakel Tekst-naar-Spraak API in via Google Cloud Console",
            googleVoiceLabel = "Stem",
            languageLabel = "Taal",
            saveButton = "Opslaan",
            savedButton = "Opgeslagen!",
            apiConfigSection = "API Configuratie",
            storyLibraryTitle = "Verhalen Bibliotheek",
            storyCount = "%d verhalen opgeslagen",
            deleteStoryTitle = "Verhaal Verwijderen",
            deleteStoryMessage = "\"%s\" verwijderen?",
            deleteAllTitle = "Alles Verwijderen",
            deleteAllMessage = "Weet je het zeker? Dit kan niet ongedaan worden gemaakt.",
            deleteAllButton = "Alles Verwijderen",
            emptyLibraryTitle = "Nog geen verhalen!",
            emptyLibrarySubtitle = "Ga naar Home en maak je eerste verhaal",
            showLess = "Minder tonen",
            readMore = "Meer lezen",
            readAloud = "Hardop Lezen",
            promptPrefix = "Prompt",
            deleteButton = "Verwijderen",
            cancelButton = "Annuleren",
            styleFairyTale = "Sprookje",
            styleAdventure = "Avontuur",
            styleFunny = "Grappig",
            styleSpooky = "Eng (zacht)",
            styleAnimal = "Dierenverhaal",
            styleSpace = "Ruimteavontuur",
            stylePrincess = "Prinses en Ridder",
            styleDinosaur = "Dinosaurusverhaal",
            styleOcean = "Oceaanavontuur",
            styleMagic = "Magie en Tovenaars",
            navHome = "Home",
            navHistory = "Geschiedenis",
            navSettings = "Instellingen"
        )
    }
}
