package com.nightstory.app.ui.strings

val chineseStrings = LocalizedStrings(
    appName = "睡前故事", appTagline = "创作神奇的睡前故事", navHome = "首页", navHistory = "历史", navSettings = "设置",
    randomStoryButton = "🎲 随机故事", customStoryButton = "✏️ 自定义故事",
    customPromptLabel = "故事讲什么？", customPromptPlaceholder = "例如：一只勇敢的兔子...",
    generateCustomButton = "✨ 生成故事", generatingText = "正在创作...", readAloud = "🔊 朗读", stopButton = "停止",
    storyLibrary = "故事库", storiesSaved = "%d 个故事", noStoriesYet = "还没有故事！", noStoriesHint = "点击随机故事开始",
    deleteStory = "删除", deleteStoryConfirm = "删除「%s」？", deleteAll = "全部删除", deleteAllConfirm = "确定吗？",
    readMore = "更多", showLess = "收起", cancel = "取消", delete = "删除", share = "分享",
    settingsTitle = "设置", settingsSubtitle = "配置故事生成器", apiSettings = "API 设置",
    apiEndpoint = "API 地址", apiEndpointPlaceholder = "https://api.example.com/v1", apiEndpointHelper = "输入兼容 OpenAI 的 API 地址",
    apiKeyLabel = "API 密钥", apiKeyPlaceholder = "输入密钥", apiKeyHelper = "服务商提供的密钥",
    modelNameLabel = "模型名称", modelNamePlaceholder = "如 gpt-4o-mini", modelNameHelper = "AI 模型名称",
    storyPreferences = "故事偏好", storyLanguage = "语言", storyStyle = "风格",
    childGender = "性别", genderBoy = "男孩 👦", genderGirl = "女孩 👧", genderBoth = "不限 👫",
    ageRange = "年龄", ageBaby = "0-2岁 👶", ageToddler = "3-5岁 🧒", ageChild = "6-8岁 👦", ageOlder = "9-12岁 🧑",
    saveButton = "保存", savedButton = "已保存！", toggleVisibility = "切换",
    styleFairyTale = "童话", styleAdventure = "冒险", styleFunny = "搞笑", styleSpooky = "微恐",
    styleAnimal = "动物", styleSpace = "太空", stylePrincess = "公主骑士", styleDinosaur = "恐龙",
    styleOcean = "海洋", styleMagic = "魔法",
    langEnglish = "英语", langSpanish = "西班牙语", langFrench = "法语", langGerman = "德语", langPortuguese = "葡萄牙语",
    langChinese = "中文", langJapanese = "日语", langKorean = "韩语", langArabic = "阿拉伯语", langPersian = "波斯语",
    langHindi = "印地语", langTurkish = "土耳其语", langItalian = "意大利语", langRussian = "俄语", langDutch = "荷兰语"
)

val japaneseStrings = LocalizedStrings(
    appName = "ナイトストーリー", appTagline = "魔法のベッドタイムストーリー", navHome = "ホーム", navHistory = "履歴", navSettings = "設定",
    randomStoryButton = "🎲 ランダム", customStoryButton = "✏️ カスタム",
    customPromptLabel = "どんな話？", customPromptPlaceholder = "例：勇敢なウサギ...",
    generateCustomButton = "✨ 生成", generatingText = "作成中...", readAloud = "🔊 読み上げ", stopButton = "停止",
    storyLibrary = "ライブラリ", storiesSaved = "%d 件", noStoriesYet = "まだありません！", noStoriesHint = "ランダムをタップ",
    deleteStory = "削除", deleteStoryConfirm = "「%s」を削除？", deleteAll = "全削除", deleteAllConfirm = "本当ですか？",
    readMore = "もっと", showLess = "閉じる", cancel = "キャンセル", delete = "削除", share = "共有",
    settingsTitle = "設定", settingsSubtitle = "ジェネレーター設定", apiSettings = "API設定",
    apiEndpoint = "エンドポイント", apiEndpointPlaceholder = "https://api.example.com/v1", apiEndpointHelper = "OpenAI互換APIアドレス",
    apiKeyLabel = "APIキー", apiKeyPlaceholder = "キーを入力", apiKeyHelper = "プロバイダーのキー",
    modelNameLabel = "モデル名", modelNamePlaceholder = "例: gpt-4o-mini", modelNameHelper = "AIモデル名",
    storyPreferences = "設定", storyLanguage = "言語", storyStyle = "スタイル",
    childGender = "性別", genderBoy = "男の子 👦", genderGirl = "女の子 👧", genderBoth = "両方 👫",
    ageRange = "年齢", ageBaby = "0-2歳 👶", ageToddler = "3-5歳 🧒", ageChild = "6-8歳 👦", ageOlder = "9-12歳 🧑",
    saveButton = "保存", savedButton = "保存済！", toggleVisibility = "切替",
    styleFairyTale = "おとぎ話", styleAdventure = "冒険", styleFunny = "面白い", styleSpooky = "ちょっと怖い",
    styleAnimal = "動物", styleSpace = "宇宙", stylePrincess = "姫と騎士", styleDinosaur = "恐竜",
    styleOcean = "海", styleMagic = "魔法",
    langEnglish = "英語", langSpanish = "スペイン語", langFrench = "フランス語", langGerman = "ドイツ語", langPortuguese = "ポルトガル語",
    langChinese = "中国語", langJapanese = "日本語", langKorean = "韓国語", langArabic = "アラビア語", langPersian = "ペルシア語",
    langHindi = "ヒンディー語", langTurkish = "トルコ語", langItalian = "イタリア語", langRussian = "ロシア語", langDutch = "オランダ語"
)

val koreanStrings = LocalizedStrings(
    appName = "나이트 스토리", appTagline = "마법 같은 잠자리 이야기", navHome = "홈", navHistory = "기록", navSettings = "설정",
    randomStoryButton = "🎲 랜덤 이야기", customStoryButton = "✏️ 맞춤 이야기",
    customPromptLabel = "이야기 주제?", customPromptPlaceholder = "예: 용감한 토끼...",
    generateCustomButton = "✨ 생성", generatingText = "만드는 중...", readAloud = "🔊 읽기", stopButton = "정지",
    storyLibrary = "라이브러리", storiesSaved = "%d개", noStoriesYet = "아직 없음!", noStoriesHint = "랜덤을 탭하세요",
    deleteStory = "삭제", deleteStoryConfirm = "「%s」삭제?", deleteAll = "모두 삭제", deleteAllConfirm = "정말?",
    readMore = "더보기", showLess = "접기", cancel = "취소", delete = "삭제", share = "공유",
    settingsTitle = "설정", settingsSubtitle = "생성기 설정", apiSettings = "API 설정",
    apiEndpoint = "엔드포인트", apiEndpointPlaceholder = "https://api.example.com/v1", apiEndpointHelper = "OpenAI 호환 API 주소",
    apiKeyLabel = "API 키", apiKeyPlaceholder = "키 입력", apiKeyHelper = "제공자 키",
    modelNameLabel = "모델명", modelNamePlaceholder = "예: gpt-4o-mini", modelNameHelper = "AI 모델명",
    storyPreferences = "설정", storyLanguage = "언어", storyStyle = "스타일",
    childGender = "성별", genderBoy = "남자아이 👦", genderGirl = "여자아이 👧", genderBoth = "모두 👫",
    ageRange = "나이", ageBaby = "0-2세 👶", ageToddler = "3-5세 🧒", ageChild = "6-8세 👦", ageOlder = "9-12세 🧑",
    saveButton = "저장", savedButton = "저장됨!", toggleVisibility = "전환",
    styleFairyTale = "동화", styleAdventure = "모험", styleFunny = "재미있는", styleSpooky = "약간 무서운",
    styleAnimal = "동물", styleSpace = "우주", stylePrincess = "공주기사", styleDinosaur = "공룡",
    styleOcean = "바다", styleMagic = "마법",
    langEnglish = "영어", langSpanish = "스페인어", langFrench = "프랑스어", langGerman = "독일어", langPortuguese = "포르투갈어",
    langChinese = "중국어", langJapanese = "일본어", langKorean = "한국어", langArabic = "아랍어", langPersian = "페르시아어",
    langHindi = "힌디어", langTurkish = "터키어", langItalian = "이탈리아어", langRussian = "러시아어", langDutch = "네덜란드어"
)
