package com.nightstory.app.ui.strings

val englishStrings = LocalizedStrings(
    appName = "Night Story", appTagline = "Create magical bedtime stories",
    navHome = "Home", navHistory = "History", navSettings = "Settings",
    randomStoryButton = "🎲 Random Story", customStoryButton = "✏️ Custom Story",
    customPromptLabel = "What should the story be about?", customPromptPlaceholder = "e.g. A brave rabbit who finds a rainbow...",
    generateCustomButton = "✨ Generate Story", generatingText = "Creating your story...",
    readAloud = "🔊 Read Aloud", stopButton = "Stop",
    storyLibrary = "Story Library", storiesSaved = "%d stories saved",
    noStoriesYet = "No stories yet!", noStoriesHint = "Tap Random Story to create your first one",
    deleteStory = "Delete Story", deleteStoryConfirm = "Delete \"%s\"?",
    deleteAll = "Delete All", deleteAllConfirm = "Are you sure? This cannot be undone.",
    readMore = "Read more", showLess = "Show less", cancel = "Cancel", delete = "Delete", share = "Share",
    settingsTitle = "Settings", settingsSubtitle = "Configure your story generator",
    apiSettings = "API Settings", apiEndpoint = "API Endpoint", apiEndpointPlaceholder = "https://api.example.com/v1",
    apiEndpointHelper = "Enter OpenAI-compatible API server address",
    apiKeyLabel = "API Key", apiKeyPlaceholder = "Enter your API key",
    apiKeyHelper = "API access key from your provider",
    modelNameLabel = "Model Name", modelNamePlaceholder = "e.g. gpt-4o-mini",
    modelNameHelper = "AI model name to use",
    storyPreferences = "Story Preferences", storyLanguage = "Story Language", storyStyle = "Story Style",
    childGender = "Child Gender", genderBoy = "Boy 👦", genderGirl = "Girl 👧", genderBoth = "Both 👫",
    ageRange = "Age Range", ageBaby = "0-2 years 👶", ageToddler = "3-5 years 🧒", ageChild = "6-8 years 👦", ageOlder = "9-12 years 🧑",
    saveButton = "Save Settings", savedButton = "Saved!", toggleVisibility = "Toggle visibility",
    styleFairyTale = "Fairy Tale", styleAdventure = "Adventure", styleFunny = "Funny", styleSpooky = "Spooky (mild)",
    styleAnimal = "Animal Story", styleSpace = "Space Adventure", stylePrincess = "Princess & Knight",
    styleDinosaur = "Dinosaur Story", styleOcean = "Ocean Adventure", styleMagic = "Magic & Wizards",
    langEnglish = "English", langSpanish = "Spanish", langFrench = "French", langGerman = "German",
    langPortuguese = "Portuguese", langChinese = "Chinese", langJapanese = "Japanese", langKorean = "Korean",
    langArabic = "Arabic", langPersian = "Persian", langHindi = "Hindi", langTurkish = "Turkish",
    langItalian = "Italian", langRussian = "Russian", langDutch = "Dutch"
)

val arabicStrings = LocalizedStrings(
    appName = "قصة الليل", appTagline = "أنشئ قصص خيالية قبل النوم",
    navHome = "الرئيسية", navHistory = "السجل", navSettings = "الإعدادات",
    randomStoryButton = "🎲 قصة عشوائية", customStoryButton = "✏️ قصة مخصصة",
    customPromptLabel = "ما موضوع القصة؟", customPromptPlaceholder = "مثلاً أرنب شجع يجد قوس قزح...",
    generateCustomButton = "✨ إنشاء القصة", generatingText = "جاري إنشاء القصة...",
    readAloud = "🔊 اقرأ بصوت عالٍ", stopButton = "إيقاف",
    storyLibrary = "مكتبة القصص", storiesSaved = "%d قصص محفوظة",
    noStoriesYet = "لا توجد قصص بعد!", noStoriesHint = "اضغط قصة عشوائية لإنشاء الأولى",
    deleteStory = "حذف القصة", deleteStoryConfirm = "حذف \"%s\"؟",
    deleteAll = "حذف الكل", deleteAllConfirm = "هل أنت متأكد؟ لا يمكن التراجع.",
    readMore = "اقرأ المزيد", showLess = "عرض أقل", cancel = "إلغاء", delete = "حذف", share = "مشاركة",
    settingsTitle = "الإعدادات", settingsSubtitle = "configure مولد القصص",
    apiSettings = "إعدادات API", apiEndpoint = "نقطة نهاية API", apiEndpointPlaceholder = "https://api.example.com/v1",
    apiEndpointHelper = "أدخل عنوان خادم API المتوافق مع OpenAI",
    apiKeyLabel = "مفتاح API", apiKeyPlaceholder = "أدخل مفتاح API",
    apiKeyHelper = "مفتاح الوصول من مزود الخدمة",
    modelNameLabel = "اسم النموذج", modelNamePlaceholder = "مثال: gpt-4o-mini",
    modelNameHelper = "اسم نموذج الذكاء الاصطناعي",
    storyPreferences = "تفضيلات القصة", storyLanguage = "لغة القصة", storyStyle = "نمط القصة",
    childGender = "جنس الطفل", genderBoy = "ولد 👦", genderGirl = "بنت 👧", genderBoth = "كلاهما 👫",
    ageRange = "الفئة العمرية", ageBaby = "٠-٢ سنة 👶", ageToddler = "٣-٥ سنوات 🧒", ageChild = "٦-٨ سنوات 👦", ageOlder = "٩-١٢ سنة 🧑",
    saveButton = "حفظ الإعدادات", savedButton = "تم الحفظ!", toggleVisibility = "تبديل الرؤية",
    styleFairyTale = "حكاية خرافية", styleAdventure = "مغامرة", styleFunny = "ممتعة", styleSpooky = "مخيفة قليلاً",
    styleAnimal = "قصة حيوانات", styleSpace = "مغامرة فضائية", stylePrincess = "الأميرة والفارس",
    styleDinosaur = "قصة ديناصورات", styleOcean = "مغامرة محيطية", styleMagic = "سحر وسحرة",
    langEnglish = "الإنجليزية", langSpanish = "الإسبانية", langFrench = "الفرنسية", langGerman = "الألمانية",
    langPortuguese = "البرتغالية", langChinese = "الصينية", langJapanese = "اليابانية", langKorean = "الكورية",
    langArabic = "العربية", langPersian = "الفارسية", langHindi = "الهندية", langTurkish = "التركية",
    langItalian = "الإيطالية", langRussian = "الروسية", langDutch = "الهولندية"
)
