package com.nightstory.app.ui.strings

val spanishStrings = LocalizedStrings(
    appName = "Cuento Nocturno", appTagline = "Crea cuentos mágicos para dormir",
    navHome = "Inicio", navHistory = "Historial", navSettings = "Ajustes",
    randomStoryButton = "🎲 Cuento Aleatorio", customStoryButton = "✏️ Cuento Personal",
    customPromptLabel = "¿De qué tratará el cuento?", customPromptPlaceholder = "ej. Un conejito valiente...",
    generateCustomButton = "✨ Crear Cuento", generatingText = "Creando tu cuento...",
    readAloud = "🔊 Leer en voz alta", stopButton = "Detener",
    storyLibrary = "Biblioteca", storiesSaved = "%d cuentos guardados",
    noStoriesYet = "¡Aún no hay cuentos!", noStoriesHint = "Toca Cuento Aleatorio para crear el primero",
    deleteStory = "Eliminar", deleteStoryConfirm = "¿Eliminar \"%s\"?", deleteAll = "Eliminar Todos",
    deleteAllConfirm = "¿Estás seguro? No se puede deshacer.", readMore = "Leer más", showLess = "Menos",
    cancel = "Cancelar", delete = "Eliminar", share = "Compartir", settingsTitle = "Ajustes", settingsSubtitle = "Configura tu generador",
    apiSettings = "API", apiEndpoint = "Endpoint", apiEndpointPlaceholder = "https://api.example.com/v1",
    apiEndpointHelper = "Dirección del servidor API compatible con OpenAI", apiKeyLabel = "Clave API",
    apiKeyPlaceholder = "Tu clave API", apiKeyHelper = "Clave de acceso del proveedor",
    modelNameLabel = "Modelo", modelNamePlaceholder = "ej. gpt-4o-mini", modelNameHelper = "Nombre del modelo IA",
    storyPreferences = "Preferencias", storyLanguage = "Idioma", storyStyle = "Estilo",
    childGender = "Género", genderBoy = "Niño 👦", genderGirl = "Niña 👧", genderBoth = "Ambos 👫",
    ageRange = "Edad", ageBaby = "0-2 👶", ageToddler = "3-5 🧒", ageChild = "6-8 👦", ageOlder = "9-12 🧑",
    saveButton = "Guardar", savedButton = "¡Guardado!", toggleVisibility = "Alternar",
    styleFairyTale = "Cuento de Hadas", styleAdventure = "Aventura", styleFunny = "Divertido",
    styleSpooky = "Algo Escalofriante", styleAnimal = "Animales", styleSpace = "Espacio",
    stylePrincess = "Princesa y Caballero", styleDinosaur = "Dinosaurios", styleOcean = "Mar", styleMagic = "Magia",
    langEnglish = "Inglés", langSpanish = "Español", langFrench = "Francés", langGerman = "Alemán",
    langPortuguese = "Portugués", langChinese = "Chino", langJapanese = "Japonés", langKorean = "Coreano",
    langArabic = "Árabe", langPersian = "Persa", langHindi = "Hindi", langTurkish = "Turco",
    langItalian = "Italiano", langRussian = "Ruso", langDutch = "Holandés"
)

val frenchStrings = LocalizedStrings(
    appName = "Conte de Nuit", appTagline = "Créez des contes magiques",
    navHome = "Accueil", navHistory = "Historique", navSettings = "Paramètres",
    randomStoryButton = "🎲 Conte Aléatoire", customStoryButton = "✏️ Conte Personnalisé",
    customPromptLabel = "De quoi parlera l'histoire ?", customPromptPlaceholder = "ex. Un lapin courageux...",
    generateCustomButton = "✨ Créer", generatingText = "Création...",
    readAloud = "🔊 Lire", stopButton = "Arrêter",
    storyLibrary = "Bibliothèque", storiesSaved = "%d histoires", noStoriesYet = "Pas encore d'histoires !",
    noStoriesHint = "Appuyez sur Conte Aléatoire", deleteStory = "Supprimer", deleteStoryConfirm = "Supprimer \"%s\" ?",
    deleteAll = "Tout Supprimer", deleteAllConfirm = "Êtes-vous sûr ?", readMore = "Lire la suite", showLess = "Réduire",
    cancel = "Annuler", delete = "Supprimer", share = "Partager", settingsTitle = "Paramètres", settingsSubtitle = "Configurez votre générateur",
    apiSettings = "API", apiEndpoint = "Endpoint", apiEndpointPlaceholder = "https://api.example.com/v1",
    apiEndpointHelper = "Adresse du serveur API compatible OpenAI", apiKeyLabel = "Clé API", apiKeyPlaceholder = "Votre clé API",
    apiKeyHelper = "Clé d'accès du fournisseur", modelNameLabel = "Modèle", modelNamePlaceholder = "ex. gpt-4o-mini",
    modelNameHelper = "Nom du modèle IA", storyPreferences = "Préférences", storyLanguage = "Langue", storyStyle = "Style",
    childGender = "Genre", genderBoy = "Garçon 👦", genderGirl = "Fille 👧", genderBoth = "Les deux 👫",
    ageRange = "Âge", ageBaby = "0-2 👶", ageToddler = "3-5 🧒", ageChild = "6-8 👦", ageOlder = "9-12 🧑",
    saveButton = "Enregistrer", savedButton = "Enregistré !", toggleVisibility = "Basculer",
    styleFairyTale = "Conte de Fées", styleAdventure = "Aventure", styleFunny = "Drôle", styleSpooky = "Effrayant",
    styleAnimal = "Animaux", styleSpace = "Espace", stylePrincess = "Princesse", styleDinosaur = "Dinosaures",
    styleOcean = "Océan", styleMagic = "Magie",
    langEnglish = "Anglais", langSpanish = "Espagnol", langFrench = "Français", langGerman = "Allemand",
    langPortuguese = "Portugais", langChinese = "Chinois", langJapanese = "Japonais", langKorean = "Coréen",
    langArabic = "Arabe", langPersian = "Persan", langHindi = "Hindi", langTurkish = "Turc",
    langItalian = "Italien", langRussian = "Russe", langDutch = "Néerlandais"
)

val germanStrings = LocalizedStrings(
    appName = "Nachtgeschichte", appTagline = "Erstelle magische Schlafgeschichten",
    navHome = "Startseite", navHistory = "Verlauf", navSettings = "Einstellungen",
    randomStoryButton = "🎲 Zufällige Geschichte", customStoryButton = "✏️ Eigene Geschichte",
    customPromptLabel = "Worum soll es gehen?", customPromptPlaceholder = "z.B. Ein mutiges Häschen...",
    generateCustomButton = "✨ Erstellen", generatingText = "Wird erstellt...",
    readAloud = "🔊 Vorlesen", stopButton = "Stopp",
    storyLibrary = "Bibliothek", storiesSaved = "%d Geschichten", noStoriesYet = "Noch keine!",
    noStoriesHint = "Tippe auf Zufällig", deleteStory = "Löschen", deleteStoryConfirm = "\"%s\" löschen?",
    deleteAll = "Alle Löschen", deleteAllConfirm = "Sicher?", readMore = "Mehr", showLess = "Weniger",
    cancel = "Abbrechen", delete = "Löschen", share = "Teilen", settingsTitle = "Einstellungen", settingsSubtitle = "Generator konfigurieren",
    apiSettings = "API", apiEndpoint = "Endpoint", apiEndpointPlaceholder = "https://api.example.com/v1",
    apiEndpointHelper = "OpenAI-kompatible API-Adresse", apiKeyLabel = "API-Schlüssel", apiKeyPlaceholder = "Ihr Schlüssel",
    apiKeyHelper = "Zugriffsschlüssel", modelNameLabel = "Modell", modelNamePlaceholder = "z.B. gpt-4o-mini",
    modelNameHelper = "KI-Modellname", storyPreferences = "Einstellungen", storyLanguage = "Sprache", storyStyle = "Stil",
    childGender = "Geschlecht", genderBoy = "Junge 👦", genderGirl = "Mädchen 👧", genderBoth = "Beide 👫",
    ageRange = "Alter", ageBaby = "0-2 👶", ageToddler = "3-5 🧒", ageChild = "6-8 👦", ageOlder = "9-12 🧑",
    saveButton = "Speichern", savedButton = "Gespeichert!", toggleVisibility = "Umschalten",
    styleFairyTale = "Märchen", styleAdventure = "Abenteuer", styleFunny = "Lustig", styleSpooky = "Gruselig",
    styleAnimal = "Tiere", styleSpace = "Weltraum", stylePrincess = "Prinzessin", styleDinosaur = "Dinosaurier",
    styleOcean = "Meer", styleMagic = "Magie",
    langEnglish = "Englisch", langSpanish = "Spanisch", langFrench = "Französisch", langGerman = "Deutsch",
    langPortuguese = "Portugiesisch", langChinese = "Chinesisch", langJapanese = "Japanisch", langKorean = "Koreanisch",
    langArabic = "Arabisch", langPersian = "Persisch", langHindi = "Hindi", langTurkish = "Türkisch",
    langItalian = "Italienisch", langRussian = "Russisch", langDutch = "Niederländisch"
)

val portugueseStrings = LocalizedStrings(
    appName = "História Noturna", appTagline = "Crie histórias mágicas",
    navHome = "Início", navHistory = "Histórico", navSettings = "Configurações",
    randomStoryButton = "🎲 História Aleatória", customStoryButton = "✏️ História Personalizada",
    customPromptLabel = "Sobre o que será?", customPromptPlaceholder = "ex. Um coelho corajoso...",
    generateCustomButton = "✨ Criar", generatingText = "Criando...",
    readAloud = "🔊 Ler", stopButton = "Parar",
    storyLibrary = "Biblioteca", storiesSaved = "%d histórias", noStoriesYet = "Nenhuma ainda!",
    noStoriesHint = "Toque em Aleatória", deleteStory = "Excluir", deleteStoryConfirm = "Excluir \"%s\"?",
    deleteAll = "Excluir Todas", deleteAllConfirm = "Tem certeza?", readMore = "Mais", showLess = "Menos",
    cancel = "Cancelar", delete = "Excluir", share = "Compartilhar", settingsTitle = "Configurações", settingsSubtitle = "Configure o gerador",
    apiSettings = "API", apiEndpoint = "Endpoint", apiEndpointPlaceholder = "https://api.example.com/v1",
    apiEndpointHelper = "Endereço do servidor API compatível com OpenAI", apiKeyLabel = "Chave API", apiKeyPlaceholder = "Sua chave",
    apiKeyHelper = "Chave de acesso", modelNameLabel = "Modelo", modelNamePlaceholder = "ex. gpt-4o-mini",
    modelNameHelper = "Nome do modelo IA", storyPreferences = "Preferências", storyLanguage = "Idioma", storyStyle = "Estilo",
    childGender = "Gênero", genderBoy = "Menino 👦", genderGirl = "Menina 👧", genderBoth = "Ambos 👫",
    ageRange = "Idade", ageBaby = "0-2 👶", ageToddler = "3-5 🧒", ageChild = "6-8 👦", ageOlder = "9-12 🧑",
    saveButton = "Salvar", savedButton = "Salvo!", toggleVisibility = "Alternar",
    styleFairyTale = "Conto de Fadas", styleAdventure = "Aventura", styleFunny = "Engraçado", styleSpooky = "Assustador",
    styleAnimal = "Animais", styleSpace = "Espaço", stylePrincess = "Princesa", styleDinosaur = "Dinossauros",
    styleOcean = "Mar", styleMagic = "Magia",
    langEnglish = "Inglês", langSpanish = "Espanhol", langFrench = "Francês", langGerman = "Alemão",
    langPortuguese = "Português", langChinese = "Chinês", langJapanese = "Japonês", langKorean = "Coreano",
    langArabic = "Árabe", langPersian = "Persa", langHindi = "Hindi", langTurkish = "Turco",
    langItalian = "Italiano", langRussian = "Russo", langDutch = "Holandês"
)
