package com.nightstory.app.ui.strings

val hindiStrings = LocalizedStrings(
    appName = "नाइट स्टोरी", appTagline = "जादुई कहानियाँ बनाएँ", navHome = "होम", navHistory = "इतिहास", navSettings = "सेटिंग्स",
    randomStoryButton = "🎲 यादृच्छिक कहानी", customStoryButton = "✏️ कस्टम कहानी",
    customPromptLabel = "कहानी किस बारे में?", customPromptPlaceholder = "जैसे एक बहादुर खरगोश...",
    generateCustomButton = "✨ बनाएँ", generatingText = "बना रहे हैं...", readAloud = "🔊 पढ़ें", stopButton = "रोकें",
    storyLibrary = "पुस्तकालय", storiesSaved = "%d कहानियाँ", noStoriesYet = "अभी कोई नहीं!", noStoriesHint = "यादृच्छिक दबाएँ",
    deleteStory = "हटाएँ", deleteStoryConfirm = "\"%s\" हटाएँ?", deleteAll = "सभी हटाएँ", deleteAllConfirm = "पक्का?",
    readMore = "और पढ़ें", showLess = "कम", cancel = "रद्द", delete = "हटाएँ", share = "साझा करें",
    settingsTitle = "सेटिंग्स", settingsSubtitle = "कॉन्फ़िगर करें", apiSettings = "API सेटिंग्स",
    apiEndpoint = "एंडपॉइंट", apiEndpointPlaceholder = "https://api.example.com/v1", apiEndpointHelper = "OpenAI संगत API पता",
    apiKeyLabel = "API कुंजी", apiKeyPlaceholder = "कुंजी दर्ज करें", apiKeyHelper = "प्रदाता से कुंजी",
    modelNameLabel = "मॉडल", modelNamePlaceholder = "जैसे gpt-4o-mini", modelNameHelper = "AI मॉडल नाम",
    storyPreferences = "प्राथमिकताएँ", storyLanguage = "भाषा", storyStyle = "शैली",
    childGender = "लिंग", genderBoy = "लड़का 👦", genderGirl = "लड़की 👧", genderBoth = "दोनों 👫",
    ageRange = "आयु", ageBaby = "0-2 👶", ageToddler = "3-5 🧒", ageChild = "6-8 👦", ageOlder = "9-12 🧑",
    saveButton = "सहेजें", savedButton = "सहेजा!", toggleVisibility = "टॉगल",
    styleFairyTale = "परी कथा", styleAdventure = "साहसिक", styleFunny = "मज़ेदार", styleSpooky = "डरावना",
    styleAnimal = "जानवर", styleSpace = "अंतरिक्ष", stylePrincess = "राजकुमारी", styleDinosaur = "डायनासोर",
    styleOcean = "समुद्र", styleMagic = "जादू",
    langEnglish = "अंग्रेज़ी", langSpanish = "स्पेनिश", langFrench = "फ़्रेंच", langGerman = "जर्मन", langPortuguese = "पुर्तगाली",
    langChinese = "चीनी", langJapanese = "जापानी", langKorean = "कोरियाई", langArabic = "अरबी", langPersian = "फ़ारसी",
    langHindi = "हिन्दी", langTurkish = "तुर्की", langItalian = "इतालवी", langRussian = "रूसी", langDutch = "डच"
)

val turkishStrings = LocalizedStrings(
    appName = "Gece Masalı", appTagline = "Büyülü masallar oluşturun", navHome = "Ana Sayfa", navHistory = "Geçmiş", navSettings = "Ayarlar",
    randomStoryButton = "🎲 Rastgele Masal", customStoryButton = "✏️ Özel Masal",
    customPromptLabel = "Masal ne hakkında?", customPromptPlaceholder = "örn. Cesur bir tavşan...",
    generateCustomButton = "✨ Oluştur", generatingText = "Oluşturuluyor...", readAloud = "🔊 Oku", stopButton = "Durdur",
    storyLibrary = "Kütüphane", storiesSaved = "%d masal", noStoriesYet = "Henüz yok!", noStoriesHint = "Rastgele dokunun",
    deleteStory = "Sil", deleteStoryConfirm = "\"%s\" silinsin mi?", deleteAll = "Tümünü Sil", deleteAllConfirm = "Emin misiniz?",
    readMore = "Daha fazla", showLess = "Daha az", cancel = "İptal", delete = "Sil", share = "Paylaş",
    settingsTitle = "Ayarlar", settingsSubtitle = "Yapılandır", apiSettings = "API Ayarları",
    apiEndpoint = "Uç Nokta", apiEndpointPlaceholder = "https://api.example.com/v1", apiEndpointHelper = "OpenAI uyumlu API adresi",
    apiKeyLabel = "API Anahtarı", apiKeyPlaceholder = "Anahtar girin", apiKeyHelper = "Sağlayıcı anahtarı",
    modelNameLabel = "Model", modelNamePlaceholder = "örn. gpt-4o-mini", modelNameHelper = "AI model adı",
    storyPreferences = "Tercihler", storyLanguage = "Dil", storyStyle = "Stil",
    childGender = "Cinsiyet", genderBoy = "Erkek 👦", genderGirl = "Kız 👧", genderBoth = "İkisi 👫",
    ageRange = "Yaş", ageBaby = "0-2 👶", ageToddler = "3-5 🧒", ageChild = "6-8 👦", ageOlder = "9-12 🧑",
    saveButton = "Kaydet", savedButton = "Kaydedildi!", toggleVisibility = "Değiştir",
    styleFairyTale = "Peri Masalı", styleAdventure = "Macera", styleFunny = "Komik", styleSpooky = "Korkunç",
    styleAnimal = "Hayvan", styleSpace = "Uzay", stylePrincess = "Prenses", styleDinosaur = "Dinozor",
    styleOcean = "Okyanus", styleMagic = "Büyü",
    langEnglish = "İngilizce", langSpanish = "İspanyolca", langFrench = "Fransızca", langGerman = "Almanca", langPortuguese = "Portekizce",
    langChinese = "Çince", langJapanese = "Japonca", langKorean = "Korece", langArabic = "Arapça", langPersian = "Farsça",
    langHindi = "Hintçe", langTurkish = "Türkçe", langItalian = "İtalyanca", langRussian = "Rusça", langDutch = "Felemenkçe"
)

val italianStrings = LocalizedStrings(
    appName = "Fiaba Notturna", appTagline = "Crea fiabe magiche", navHome = "Home", navHistory = "Cronologia", navSettings = "Impostazioni",
    randomStoryButton = "🎲 Storia Casuale", customStoryButton = "✏️ Storia Personalizzata",
    customPromptLabel = "Di cosa parlerà?", customPromptPlaceholder = "es. Un coniglietto coraggioso...",
    generateCustomButton = "✨ Crea", generatingText = "Creazione...", readAloud = "🔊 Leggi", stopButton = "Ferma",
    storyLibrary = "Libreria", storiesSaved = "%d storie", noStoriesYet = "Nessuna storia!", noStoriesHint = "Tocca Casuale",
    deleteStory = "Elimina", deleteStoryConfirm = "Eliminare \"%s\"?", deleteAll = "Elimina Tutto", deleteAllConfirm = "Sicuro?",
    readMore = "Leggi", showLess = "Meno", cancel = "Annulla", delete = "Elimina", share = "Condividi",
    settingsTitle = "Impostazioni", settingsSubtitle = "Configura", apiSettings = "API",
    apiEndpoint = "Endpoint", apiEndpointPlaceholder = "https://api.example.com/v1", apiEndpointHelper = "Indirizzo API compatibile OpenAI",
    apiKeyLabel = "Chiave API", apiKeyPlaceholder = "Inserisci chiave", apiKeyHelper = "Chiave del fornitore",
    modelNameLabel = "Modello", modelNamePlaceholder = "es. gpt-4o-mini", modelNameHelper = "Nome modello IA",
    storyPreferences = "Preferenze", storyLanguage = "Lingua", storyStyle = "Stile",
    childGender = "Genere", genderBoy = "Ragazzo 👦", genderGirl = "Ragazza 👧", genderBoth = "Entrambi 👫",
    ageRange = "Età", ageBaby = "0-2 👶", ageToddler = "3-5 🧒", ageChild = "6-8 👦", ageOlder = "9-12 🧑",
    saveButton = "Salva", savedButton = "Salvato!", toggleVisibility = "Alterna",
    styleFairyTale = "Fiaba", styleAdventure = "Avventura", styleFunny = "Divertente", styleSpooky = "Spaventoso",
    styleAnimal = "Animali", styleSpace = "Spazio", stylePrincess = "Principessa", styleDinosaur = "Dinosauri",
    styleOcean = "Mare", styleMagic = "Magia",
    langEnglish = "Inglese", langSpanish = "Spagnolo", langFrench = "Francese", langGerman = "Tedesco", langPortuguese = "Portoghese",
    langChinese = "Cinese", langJapanese = "Giapponese", langKorean = "Coreano", langArabic = "Arabo", langPersian = "Persiano",
    langHindi = "Hindi", langTurkish = "Turco", langItalian = "Italiano", langRussian = "Russo", langDutch = "Olandese"
)

val russianStrings = LocalizedStrings(
    appName = "Ночная Сказка", appTagline = "Создавайте волшебные сказки", navHome = "Главная", navHistory = "История", navSettings = "Настройки",
    randomStoryButton = "🎲 Случайная", customStoryButton = "✏️ Своя Сказка",
    customPromptLabel = "О чём сказка?", customPromptPlaceholder = "напр. Храбрый зайчик...",
    generateCustomButton = "✨ Создать", generatingText = "Создание...", readAloud = "🔊 Читать", stopButton = "Стоп",
    storyLibrary = "Библиотека", storiesSaved = "%d сказок", noStoriesYet = "Пока нет!", noStoriesHint = "Нажмите Случайная",
    deleteStory = "Удалить", deleteStoryConfirm = "Удалить «%s»?", deleteAll = "Удалить Все", deleteAllConfirm = "Уверены?",
    readMore = "Далее", showLess = "Свернуть", cancel = "Отмена", delete = "Удалить", share = "Поделиться",
    settingsTitle = "Настройки", settingsSubtitle = "Настройка генератора", apiSettings = "API",
    apiEndpoint = "Эндпоинт", apiEndpointPlaceholder = "https://api.example.com/v1", apiEndpointHelper = "Адрес API совместимый с OpenAI",
    apiKeyLabel = "API-ключ", apiKeyPlaceholder = "Введите ключ", apiKeyHelper = "Ключ от провайдера",
    modelNameLabel = "Модель", modelNamePlaceholder = "напр. gpt-4o-mini", modelNameHelper = "Название модели ИИ",
    storyPreferences = "Настройки", storyLanguage = "Язык", storyStyle = "Стиль",
    childGender = "Пол", genderBoy = "Мальчик 👦", genderGirl = "Девочка 👧", genderBoth = "Оба 👫",
    ageRange = "Возраст", ageBaby = "0-2 👶", ageToddler = "3-5 🧒", ageChild = "6-8 👦", ageOlder = "9-12 🧑",
    saveButton = "Сохранить", savedButton = "Сохранено!", toggleVisibility = "Переключить",
    styleFairyTale = "Сказка", styleAdventure = "Приключение", styleFunny = "Смешная", styleSpooky = "Страшная",
    styleAnimal = "Животные", styleSpace = "Космос", stylePrincess = "Принцесса", styleDinosaur = "Динозавры",
    styleOcean = "Океан", styleMagic = "Магия",
    langEnglish = "Английский", langSpanish = "Испанский", langFrench = "Французский", langGerman = "Немецкий", langPortuguese = "Португальский",
    langChinese = "Китайский", langJapanese = "Японский", langKorean = "Корейский", langArabic = "Арабский", langPersian = "Персидский",
    langHindi = "Хинди", langTurkish = "Турецкий", langItalian = "Итальянский", langRussian = "Русский", langDutch = "Голландский"
)

val dutchStrings = LocalizedStrings(
    appName = "Nachtverhaal", appTagline = "Maak magische verhalen", navHome = "Home", navHistory = "Geschiedenis", navSettings = "Instellingen",
    randomStoryButton = "🎲 Willekeurig", customStoryButton = "✏️ Eigen Verhaal",
    customPromptLabel = "Waarover?", customPromptPlaceholder = "bijv. Een dapper konijntje...",
    generateCustomButton = "✨ Maken", generatingText = "Maken...", readAloud = "🔊 Lezen", stopButton = "Stop",
    storyLibrary = "Bibliotheek", storiesSaved = "%d verhalen", noStoriesYet = "Nog geen!", noStoriesHint = "Tik Willekeurig",
    deleteStory = "Verwijderen", deleteStoryConfirm = "\"%s\" verwijderen?", deleteAll = "Alles Verwijderen", deleteAllConfirm = "Zeker?",
    readMore = "Meer", showLess = "Minder", cancel = "Annuleren", delete = "Verwijderen", share = "Delen",
    settingsTitle = "Instellingen", settingsSubtitle = "Configureer", apiSettings = "API",
    apiEndpoint = "Endpoint", apiEndpointPlaceholder = "https://api.example.com/v1", apiEndpointHelper = "OpenAI-compatibel API adres",
    apiKeyLabel = "API-sleutel", apiKeyPlaceholder = "Sleutel invoeren", apiKeyHelper = "Sleutel van provider",
    modelNameLabel = "Model", modelNamePlaceholder = "bijv. gpt-4o-mini", modelNameHelper = "AI modelnaam",
    storyPreferences = "Voorkeuren", storyLanguage = "Taal", storyStyle = "Stijl",
    childGender = "Geslacht", genderBoy = "Jongen 👦", genderGirl = "Meisje 👧", genderBoth = "Beide 👫",
    ageRange = "Leeftijd", ageBaby = "0-2 👶", ageToddler = "3-5 🧒", ageChild = "6-8 👦", ageOlder = "9-12 🧑",
    saveButton = "Opslaan", savedButton = "Opgeslagen!", toggleVisibility = "Wisselen",
    styleFairyTale = "Sprookje", styleAdventure = "Avontuur", styleFunny = "Grappig", styleSpooky = "Griezelig",
    styleAnimal = "Dieren", styleSpace = "Ruimte", stylePrincess = "Prinses", styleDinosaur = "Dino",
    styleOcean = "Oceaan", styleMagic = "Magie",
    langEnglish = "Engels", langSpanish = "Spaans", langFrench = "Frans", langGerman = "Duits", langPortuguese = "Portugees",
    langChinese = "Chinees", langJapanese = "Japans", langKorean = "Koreaans", langArabic = "Arabisch", langPersian = "Perzisch",
    langHindi = "Hindi", langTurkish = "Turks", langItalian = "Italiaans", langRussian = "Russisch", langDutch = "Nederlands"
)
